import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Clock, FileText, MessageCircle, Printer, RefreshCw, Search, Wallet } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { cn } from '@/lib/utils';

export interface OverdueWorkspaceItem {
  key: string; title: string; subtitle?: string; amount: number; date: string; days: number;
  contract?: string; amountLabel?: string; dateLabel?: string; breakdown?: ReactNode; onSettle: () => void; onReminder: () => void;
  reminderDisabled?: boolean; onPrint?: () => void;
}
export interface OverdueWorkspaceCustomer {
  key: string; name: string; amount: number; count: number; days: number; phone?: string;
  items: OverdueWorkspaceItem[]; extra?: ReactNode; onAccount: () => void;
  onReminder: () => void; reminderDisabled?: boolean; onPrint?: () => void;
}
const money = (value: number) => `${Number(value || 0).toLocaleString('ar-LY')} د.ل`;
export function OverdueWorkspace({ title, description, itemLabel, customers, totalAmount, totalItems, search, onSearch, minDays, onMinDays, minAmount, onMinAmount, sort, onSort, onRefresh, headerAction }: {
  title: string; description: string; itemLabel: string; customers: OverdueWorkspaceCustomer[];
  totalAmount: number; totalItems: number; search: string; onSearch: (value: string) => void;
  minDays: number; onMinDays: (value: number) => void; minAmount: string; onMinAmount: (value: string) => void;
  sort: string; onSort: (value: 'oldest' | 'newest') => void; onRefresh: () => void; headerAction?: ReactNode;
}) {
  const [selectedKey, setSelectedKey] = useState<string | null>(null);
  const [limit, setLimit] = useState(30);
  const detailRef = useRef<HTMLElement>(null);
  useEffect(() => { setLimit(30); }, [search, minDays, minAmount, sort]);
  const selected = customers.find(c => c.key === selectedKey) || customers[0];
  const choose = (key: string) => {
    setSelectedKey(key);
    if (window.innerWidth < 1024) requestAnimationFrame(() => detailRef.current?.scrollIntoView({ block: 'start', behavior: 'auto' }));
  };
  return <div className="mx-auto max-w-[1500px] space-y-4 p-3 sm:p-5 [&_button]:cursor-pointer [&_button]:transition-colors [&_button]:duration-200" dir="rtl">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><p className="mb-1 text-xs font-medium text-primary">متابعة التحصيل</p><h1 className="text-xl font-bold sm:text-2xl">{title}</h1><p className="mt-1 max-w-2xl text-xs leading-relaxed text-muted-foreground">{description}</p></div><div className="flex flex-wrap gap-2">{headerAction}<Button variant="outline" size="sm" className="h-10" onClick={onRefresh}><RefreshCw className="h-4 w-4"/>تحديث</Button></div></header>
    <dl className="grid grid-cols-3 gap-2 sm:gap-3">{[{label:'المستحق للتحصيل',value:money(totalAmount),accent:true},{label:'الزبائن',value:customers.length},{label:itemLabel,value:totalItems}].map(stat=><div key={stat.label} className="min-w-0 rounded-xl border border-border bg-card p-3 sm:p-4"><dt className="text-[11px] text-muted-foreground">{stat.label}</dt><dd className={cn('mt-2 break-words text-base font-bold tabular-nums sm:text-xl',stat.accent&&'text-primary')}>{stat.value}</dd></div>)}</dl>
    <section className="rounded-xl border border-border bg-card p-3" aria-label="البحث والتصفية"><div className="flex flex-wrap gap-2"><div className="relative min-w-[180px] flex-1"><Search className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>onSearch(e.target.value.slice(0,100))} placeholder="ابحث باسم الزبون..." aria-label="البحث عن زبون" className="h-10 pr-9"/></div><Select value={String(minDays)} onValueChange={v=>onMinDays(Number(v))}><SelectTrigger className="h-10 w-full text-xs sm:w-44" aria-label="مدة التأخير"><SelectValue/></SelectTrigger><SelectContent>{[{value:0,label:'كل مدد التأخير'},{value:7,label:'7 أيام وأكثر'},{value:30,label:'30 يومًا وأكثر'},{value:60,label:'60 يومًا وأكثر'},{value:90,label:'90 يومًا وأكثر'}].map(option=><SelectItem key={option.value} value={String(option.value)}>{option.label}</SelectItem>)}</SelectContent></Select><Select value={sort} onValueChange={v=>onSort(v as 'oldest'|'newest')}><SelectTrigger className="h-10 w-full text-xs sm:w-40" aria-label="ترتيب المتأخرات"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="oldest">الأقدم أولًا</SelectItem><SelectItem value="newest">الأحدث أولًا</SelectItem></SelectContent></Select></div><details className="mt-3 border-t border-border pt-2"><summary className="cursor-pointer text-xs text-muted-foreground">تصفية المبلغ</summary><div className="mt-3 flex flex-wrap gap-2"><Input aria-label="الحد الأدنى للمبلغ" type="number" min={0} value={minAmount} onChange={e=>onMinAmount(e.target.value.slice(0,12))} placeholder="الحد الأدنى للمبلغ (د.ل)" className="h-10 w-full sm:w-64"/><Button variant="ghost" size="sm" onClick={()=>{onSearch('');onMinDays(0);onMinAmount('');onSort('oldest');}}>مسح التصفية</Button></div></details></section>
    {!selected ? <div className="rounded-xl border border-dashed border-border bg-card p-12 text-center"><Wallet className="mx-auto mb-3 h-8 w-8 text-muted-foreground"/><p className="font-semibold">لا توجد متأخرات مطابقة</p><p className="mt-1 text-xs text-muted-foreground">غيّر البحث أو خيارات التصفية لعرض نتائج أخرى.</p></div> : <div className="grid items-start gap-4 lg:grid-cols-[300px_minmax(0,1fr)] xl:grid-cols-[340px_minmax(0,1fr)]">
      <aside className="min-w-0 rounded-xl border border-border bg-card p-3"><h2 className="mb-3 text-sm font-bold">الزبائن ({customers.length})</h2><div className="max-h-80 space-y-2 overflow-y-auto lg:max-h-[calc(100vh-330px)]">{customers.slice(0,limit).map(customer=><button key={customer.key} type="button" onClick={()=>choose(customer.key)} aria-pressed={selected.key===customer.key} className={cn('w-full rounded-lg border p-3 text-right hover:border-primary/50',selected.key===customer.key?'border-primary bg-primary/5':'border-border')}><div className="flex items-start justify-between gap-2"><h3 className="min-w-0 flex-1 break-words text-[13px] font-bold">{customer.name}</h3><span className="shrink-0 text-[12px] font-semibold tabular-nums text-primary">{money(customer.amount)}</span></div><p className="mt-2 text-[11px] text-muted-foreground">{customer.count} {itemLabel} · أقدم تأخير {customer.days} يوم</p></button>)}</div>{customers.length>limit&&<Button variant="ghost" className="mt-2 w-full" onClick={()=>setLimit(v=>v+30)}>عرض المزيد</Button>}</aside>
      <section ref={detailRef} className="min-w-0 scroll-mt-16 overflow-hidden rounded-xl border border-border bg-card" aria-label="تفاصيل المتأخرات"><header className="border-b border-border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{selected.name}</h2><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><Clock className="h-3.5 w-3.5"/>أقدم تأخير {selected.days} يوم · {selected.count} {itemLabel}</p>{selected.phone&&<p className="mt-1 text-xs text-muted-foreground"><bdi dir="ltr">{selected.phone}</bdi></p>}</div><div><p className="text-[11px] text-muted-foreground">المستحق على الزبون</p><p className="mt-1 text-xl font-bold tabular-nums text-primary">{money(selected.amount)}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" className="h-10" onClick={selected.onAccount}><FileText className="h-4 w-4"/>فتح كشف الحساب</Button>{selected.onPrint&&<Button size="sm" variant="outline" className="h-10" onClick={selected.onPrint}><Printer className="h-4 w-4"/>طباعة الكشف</Button>}<Button size="sm" variant="outline" className="h-10" disabled={selected.reminderDisabled} onClick={selected.onReminder}><MessageCircle className="h-4 w-4"/>تذكير الزبون</Button></div></header>
        <div className="space-y-3 p-3 sm:p-4">{selected.extra}<h3 className="text-sm font-bold">تفاصيل {itemLabel}</h3>{selected.items.map(item=><article key={item.key} className="rounded-xl border border-border p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap gap-2 text-[11px] text-muted-foreground">{item.contract&&<span>{item.contract}</span>}<span className={cn('rounded-md px-2 py-0.5',item.days>=90?'bg-destructive/10 text-destructive':item.days>=30?'bg-warning/10 text-warning':'bg-muted text-muted-foreground')}>{item.days} يوم تأخير</span></div><h4 className="break-words text-[13px] font-semibold">{item.title}</h4>{item.subtitle&&<p className="mt-1 break-words text-xs leading-relaxed text-muted-foreground">{item.subtitle}</p>}<p className="mt-2 text-[11px] text-muted-foreground">{item.dateLabel || 'التاريخ'}: {item.date ? new Date(item.date).toLocaleDateString('ar-LY') : 'غير محدد'}</p></div><div className="shrink-0"><p className="text-[10px] text-muted-foreground">{item.amountLabel || 'المتبقي المطلوب'}</p><p className="mt-1 text-base font-bold tabular-nums">{money(item.amount)}</p></div></div>{item.breakdown}<div className="mt-3 flex flex-wrap gap-2 border-t border-border pt-3"><Button size="sm" className="h-10" onClick={item.onSettle}>تسديد</Button>{item.onPrint&&<Button size="sm" variant="outline" className="h-10" onClick={item.onPrint}><Printer className="h-4 w-4"/>إشعار</Button>}<Button size="sm" variant="ghost" className="h-10" disabled={item.reminderDisabled} onClick={item.onReminder}>تذكير</Button></div></article>)}</div>
      </section>
    </div>}
  </div>;
}
